spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth-ms/**  # Roteia todas as requisições que começam com /auth-ms
server:
  servlet:
    contextPath: /gateway
