spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita a descoberta automática de serviços via Eureka
          lower-case-service-id: true  # Garante que os nomes dos serviços sejam tratados em minúsculas
