spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-ms  # Nome correto do auth-service registrado no Eureka
          predicates:
            - Path=/auth-ms/**  # Roteia todas as requisições que começam com /auth-ms
server:
  servlet:
    contextPath: /gateway
